name: angular-app-backend

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.EC2_PRIVATE_KEY }}

    - name: Copy files via SCP
      run: |
        rsync -avz -e "ssh -o StrictHostKeyChecking=no" ./* ubuntu@ec2-65-2-98-244.ap-south-1.compute.amazonaws.com:/tmp/
        ssh ubuntu@ec2-65-2-98-244.ap-south-1.compute.amazonaws.com 'sudo rsync -avz /tmp/ /var/www/html/'
